dist:
  name: otelcol-custom
  description: Custom OpenTelemetry Collector with HTTP JSON Exporter for Exaforce
  output_path: ./otelcol-custom

exporters:
  - gomod: github.com/Buzzaloo/httpjson-exporter/httpjsonexporter v0.1.0
    path: ./httpjsonexporter

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowseventlogreceiver v0.114.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.114.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.114.0
